name: Deploy Nuxt app
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Deployment to machine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script:  |
            cd ~/MarinoCodes
            git pull
            npm install
            npm run build
            pm2 reload MarinoWebsite
